// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add0Lost: typeof import('./src/components/Add0Lost.vue')['default']
    Add1Lost: typeof import('./src/components/Add1Lost.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Get0Lost: typeof import('./src/components/Get0Lost.vue')['default']
    Get1Lost: typeof import('./src/components/Get1Lost.vue')['default']
    Get3Lost: typeof import('./src/components/Get3Lost.vue')['default']
    GetAllAdmin: typeof import('./src/components/GetAllAdmin.vue')['default']
    GetAllBookForAudit: typeof import('./src/components/GetAllBookForAudit.vue')['default']
    GetAllBookForAudit0: typeof import('./src/components/GetAllBookForAudit0.vue')['default']
    GetAllBookForClassroom: typeof import('./src/components/GetAllBookForClassroom.vue')['default']
    GetAllBookForUser: typeof import('./src/components/GetAllBookForUser.vue')['default']
    GetAllClassroom: typeof import('./src/components/GetAllClassroom.vue')['default']
    GetAllUser: typeof import('./src/components/GetAllUser.vue')['default']
    GetAllWorking: typeof import('./src/components/GetAllWorking.vue')['default']
    GetAllWorkingForClassroom: typeof import('./src/components/GetAllWorkingForClassroom.vue')['default']
    GetAllWorkingForUser: typeof import('./src/components/GetAllWorkingForUser.vue')['default']
    GetLostForTime: typeof import('./src/components/GetLostForTime.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    UpdateWaiter: typeof import('./src/components/UpdateWaiter.vue')['default']
    Waiterlogin: typeof import('./src/components/Waiterlogin.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
