// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Add0Lost: typeof import('./src/components/Add0Lost.vue')['default']
    Add1Lost: typeof import('./src/components/Add1Lost.vue')['default']
    AddBook: typeof import('./src/components/AddBook.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Get0Lost: typeof import('./src/components/Get0Lost.vue')['default']
    Get1Lost: typeof import('./src/components/Get1Lost.vue')['default']
    GetAllAdmin: typeof import('./src/components/GetAllAdmin.vue')['default']
    GetAllBookForUser: typeof import('./src/components/GetAllBookForUser.vue')['default']
    GetAllClassroom: typeof import('./src/components/GetAllClassroom.vue')['default']
    GetAllWaiter: typeof import('./src/components/GetAllWaiter.vue')['default']
    GetAllWorkingForUser: typeof import('./src/components/GetAllWorkingForUser.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    UpdateUser: typeof import('./src/components/UpdateUser.vue')['default']
    Userlogin: typeof import('./src/components/Userlogin.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
