// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddBook: typeof import('./src/components/BookView/AddBook.vue')['default']
    AddClassroom: typeof import('./src/components/ClassroomView/AddClassroom.vue')['default']
    AddLost: typeof import('./src/components/LostView/AddLost.vue')['default']
    AddUser: typeof import('./src/components/UserView/AddUser.vue')['default']
    AddWaiter: typeof import('./src/components/WaiterView/AddWaiter.vue')['default']
    AddWorking: typeof import('./src/components/WorkingView/AddWorking.vue')['default']
    Admlogin: typeof import('./src/components/Admlogin.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    GetAllBook: typeof import('./src/components/BookView/GetAllBook.vue')['default']
    GetAllClassroom: typeof import('./src/components/ClassroomView/GetAllClassroom.vue')['default']
    GetAllLost: typeof import('./src/components/LostView/GetAllLost.vue')['default']
    GetAllUser: typeof import('./src/components/UserView/GetAllUser.vue')['default']
    GetAllWaiter: typeof import('./src/components/WaiterView/GetAllWaiter.vue')['default']
    GetAllWorking: typeof import('./src/components/WorkingView/GetAllWorking.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    UpdateAdmin: typeof import('./src/components/UpdateAdmin.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
